# Generated by Django 2.2.10 on 2020-02-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=70)),
                ('book_edition', models.CharField(max_length=5)),
                ('book_year', models.CharField(max_length=4)),
                ('book_author', models.ForeignKey(limit_choices_to=20, on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='core.Authors')),
            ],
        ),
    ]
